version: "3.9"
name: media-stack
services:
  radarr:
    profiles: ["standard"]
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.15.1
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - media-storage:/media
    restart: "unless-stopped"

  sonarr:
    profiles: ["standard"]
    image: linuxserver/sonarr:4.0.11
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - media-storage:/media
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    profiles: ["standard"]
    container_name: prowlarr
    image: linuxserver/prowlarr:1.27.0
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    profiles: ["standard"]
    image: fallenbagel/jellyseerr:2.1.0
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    profiles: ["standard"]
    image: linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - media-storage:/data
    devices:
      - /dev/videoN:/dev/videoN # Mount GPU device (uncomment and replace N with your device number)
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  bazarr:
    profiles: ["standard"]
    container_name: bazarr
    image: linuxserver/bazarr:1.4.2
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - bazarr-config:/config
      - media-storage:/media
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  media-storage:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  jellyseerr-config:
  bazarr-config:

networks:
  mynetwork:
    external: true
